### PR TITLE
add support for array as input

### LINKED ISSUE #132: export with select not working
hi,
my code is:
$filename = "file.xlsx"
$select = array('tipo_variante', 'id_variante', 'descrizione', 'forn_descr');
 $data = DB::table($table)->select($select)->whereNull("deleted_at")->get()->toArray();
(new FastExcel($result))->export($filename);
but my excel is blank;

any help?

### PR DESCRIPTION
**Pull request by johanrosenson**
This fixes #132 

Adds support for using arrays as input and not only a collection or generator.

### CODE REVIEW

**Comment by johanrosenson** [comment]
Made a new commit that passes the tests and has a better check for arrays.

But i'm thinking if an extra else-case should be added also to throw an exception if there is no valid input (not collection, array or generator), that would be scope for a new PR, but i don't want to add that without approval or discussion.

**Comment by rap2hpoutre** [comment]
> But i'm thinking if an extra else-case should be added also to throw an exception if there is no valid input (not collection, array or generator), that would be scope for a new PR, but i don't want to add that without approval or discussion.

Sounds good to me, feel free to open a PR! 👍 What disadvantage do you see in adding an exception?

**Comment by rap2hpoutre** [comment]
Thank you again!

**Comment by rap2hpoutre** [comment]
Available in v1.5.0

**Pull request merged**
