### PR TITLE
Upgrade OpenSpout to version 4

### PR DESCRIPTION
**Pull request by dyaskur**
It will change the minimum PHP version to 8 and Laravel version to 6.

### CODE REVIEW

**Comment by lptn** [comment]
Fixes #301

Fixes #288

**Comment by rap2hpoutre** [comment]
Thank you! Sorry for late answer!

**Comment by lptn** [comment]
thanks @rap2hpoutre!

Now, the only missing part is to bump a version (tag a new release). I hope we'll have a new release soon 😀

**Comment by rap2hpoutre** [comment]
Released in 5.0.0!

**Pull request merged**
