### PR TITLE
fix: configure reader/writer options spout v4

### PR DESCRIPTION
**Pull request by atymic**
In #294, openspout was upgraded to v4. In openspout v4, you can no longer configure options on a already created writer/reader instance. 

This was kind of corrected, as #294 passes the options object, not a reader/writer object as the docblock incorrectly states, however since the `$reader_or_writer instanceof ReaderInterface` will never eval to true (since it is an options object) you can no longer configure options.

This PR corrects that by adding a method, `configureOptionsUsing` which sets the options config callback, allowing you to change settings. I also no-oped and marked as deprecated the `configureWriterUsing` and `configureReaderUsing` methods since they can't possibly actually do anything anymore. Happy to remove them instead but figured can avoid a BC break by leaving them.

Also added a test to cover the options config :)

### CODE REVIEW

**Comment by ahurov** [comment]
**up**  
that's important fix

**Comment by atymic** [comment]
@rap2hpoutre any chance of a review? Been using our fork in prod with no issues :)

**Review by robinmoisson — COMMENTED** [review]
I was going to open a PR for the same thing, then saw yours. Thank you!

One suggestion: this looks like this works well but this will be a breaking change for people who were relying on `configureWriterUsing`. I was using it with 

```php
->configureWriterUsing(function ($writer) {
  $writer->getOptions()->...
})
```

One way to keep that working would be splitting the `setOptions` method to add another method
```php
/**
 * @param \OpenSpout\Reader\ReaderInterface|\OpenSpout\Writer\WriterInterface $reader_or_writer
 */
protected function configureReaderOrWriter(&$reader_or_writer)
{
    if ($reader_or_writer instanceof ReaderInterface && is_callable($this->reader_configurator)) {
        call_user_func(
            $this->reader_configurator,
            $reader_or_writer
        );
    } elseif ($reader_or_writer instanceof WriterInterface && is_callable($this->writer_configurator)) {
        call_user_func(
            $this->writer_configurator,
            $reader_or_writer
        );
    }
}
```
and calling it in the `Exportable/Importable` traits just after we call the `$this->setOptions($options)`.

Now arguably that method using the writer/reader as argument has been broken since #311 merged on Feb 9, so maybe backward compatibility isn't a strong issue... I don't know. I had to pin my version to v5.1.0, just before #311, to keep using that method as documented.

**Comment by atymic** [comment]
> Now arguably that method using the writer/reader as argument has been broken since https://github.com/rap2hpoutre/fast-excel/pull/311 merged on Feb 9, so maybe backward compatibility isn't a strong issue... I don't know. I had to pin my version to v5.1.0, just before https://github.com/rap2hpoutre/fast-excel/pull/311, to keep using that method as documented.

That was my thought, as it's already broken. I guess the other option is just deleting those broken methods completely and just releasing a new major version?

Would be happy to split it out if @rap2hpoutre would like

**Comment by atymic** [comment]
@rap2hpoutre Any chance of a merge/review?

**Comment by atymic** [comment]
I have been using my branch for ages in prod waiting for this to get merged.


```
 {
            "type": "github",
            "url": "https://github.com/atymic/fast-excel"
        },
```
```
        "rap2hpoutre/fast-excel": "5.0.1",
```
@rap2hpoutre

**Comment by rap2hpoutre** [comment]
Thank you for your contribution and sorry for late answer!
Reviewed, accepted, merged!

**Comment by rap2hpoutre** [comment]
Available in 5.3.0 (since it's not really breaking change as you stated!)

**Comment by robinmoisson** [comment]
Awesome, thank you @rap2hpoutre!

**Comment by atymic** [comment]
Thanks @rap2hpoutre!

**Pull request merged**
