### PR TITLE
FIX: Style header not working

### PR DESCRIPTION
**Pull request by humbertleonardo**
I identified that when defining calling the headerStyle() function, it had no effect. After making the suggested modification to the file, it returned to normal operation.

### CODE REVIEW

**Comment by cbraillon** [comment]
Just had the same problem (headerStyle had no effect). With the fix of @humbertleonardo, it works perfectly !
Need this to be merged 🙏

**Comment by kusab85** [comment]
Please merge this PR. I really need header row styling in my exports.

**Comment by camsimi** [comment]
Hi @rap2hpoutre,

I also need this fix.
Is there a reason why you don't want to merge it or is it due to a lack of time ?

Thanks :pray:

**Comment by rooselle** [comment]
Hi,
Please, I also really need this fix :pray: 
Do you have any idea when it could be fixed?
Thanks!

**Comment by rap2hpoutre** [comment]
Thank you!! Sorry for late answer. Available in v5.2.0!

**Comment by camsimi** [comment]
Thanks !! :)

**Pull request merged**
